#!/usr/bin/perl -w

# Copyright (c) 2005  Rafael Laboissiere <rafael@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

=head1 NAME

octave-depends - calculates Octave dependencies

=cut

use strict;
use File::Find;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<octave-depends> [S<I<debhelper options>>]

=head1 DESCRIPTION

octave-depends is a debhelper-like program that is responsible for
generating the ${octave:Depends} substitutions and adding them to
substvars files.  Variables ${octave<major>:Depends} are also
available, where <major> is currently either "-2-1" or "-2-9" (N.B.:
periods are not allowed in substvar names).

If you use this program, your package must build-depend on octave2.1-headers
(>= 2.1.73-10) or octave2.9-headers (>= 2.9.7-2).

=cut

init ();

my $octcfg = '/usr/bin/octave-config-@VERSION@';
my $octpkg = 'octave@MAJOR@';
my $octpfx = 'octave-@MAJOR@';
$octpfx =~ s/\./-/;

# The current Octave version
my $octver = `$octcfg --version 2>&1`
	or die "Command $octcfg not found";
chomp $octver;

foreach my $package (@{$dh{DOPACKAGES}}) {

	delsubstvar($package, "octave:Depends");
	addsubstvar($package, "octave:Depends", $octpkg, ">= $octver");

	delsubstvar($package, "$octpfx:Depends");
	addsubstvar($package, "$octpfx:Depends", $octpkg, ">= $octver");
}

=head1 SEE ALSO

L<debhelper(7)>

This program is not part of debhelper.

=head1 AUTHOR

Rafael Laboissiere <rafael@debian.org>

Most ideas borrowed from dh_python by Josselin Mouette <joss@debian.org>,
who apparently took ideas from Brendan O'Dea <bod@debian.org>.

=cut
