// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cm-dm.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "dDiagMatrix.h"
MDM_BIN_OPS (ComplexMatrix, ComplexMatrix, DiagMatrix, 0.0)
