// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cs-m.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "CMatrix.h"
#include "oct-cmplx.h"
#include "dMatrix.h"
SM_BIN_OPS (ComplexMatrix, Complex, Matrix)
SM_CMP_OPS (Complex, real, Matrix, )
SM_BOOL_OPS2 (Complex, Matrix, 0.0, 0.0)
