// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cdm-m.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "dMatrix.h"
DMM_BIN_OPS (ComplexMatrix, ComplexDiagMatrix, Matrix, 0.0)
