// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cs-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "CNDArray.h"
#include "oct-cmplx.h"
#include "dNDArray.h"
SND_BIN_OPS (ComplexNDArray, Complex, NDArray)
SND_CMP_OPS (Complex, real, NDArray, )
SND_BOOL_OPS2 (Complex, NDArray, 0.0, 0.0)
