// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-dm-cs.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "dDiagMatrix.h"
#include "oct-cmplx.h"
DMS_BIN_OPS (ComplexMatrix, DiagMatrix, Complex)
