// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-dm-cm.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "dDiagMatrix.h"
DMM_BIN_OPS (ComplexMatrix, DiagMatrix, ComplexMatrix, 0.0)
