// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-i8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int8NDArray, FloatNDArray, int8NDArray)
NDND_CMP_OPS (FloatNDArray, , int8NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, int8NDArray, static_cast<float>(0.0), octave_int8::zero)
