// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcnda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "fCNDArray.h"
NDS_BIN_OPS (FloatComplexNDArray, FloatComplexNDArray, float)
NDS_CMP_OPS (FloatComplexNDArray, real, float, )
NDS_BOOL_OPS2 (FloatComplexNDArray, float, static_cast<float>(0.0), static_cast<float>(0.0))
