// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
SND_BIN_OPS (uint64NDArray, float, uint64NDArray)
SND_CMP_OPS1 (float, , uint64NDArray, , uint64_t)
SND_BOOL_OPS2 (float, uint64NDArray, static_cast<float>(0.0), octave_uint64::zero)
