// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fdm-fm.h"
#include "mx-op-defs.h"
#include "fMatrix.h"
#include "fDiagMatrix.h"
DMM_BIN_OPS (FloatMatrix, FloatDiagMatrix, FloatMatrix, static_cast<float>(0.0))
