// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint16NDArray, FloatNDArray, uint16NDArray)
NDND_CMP_OPS (FloatNDArray, , uint16NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, uint16NDArray, static_cast<float>(0.0), octave_uint16::zero)
