// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcm-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "fCMatrix.h"
MS_BIN_OPS (FloatComplexMatrix, FloatComplexMatrix, float)
MS_CMP_OPS (FloatComplexMatrix, real, float, )
MS_BOOL_OPS2 (FloatComplexMatrix, float, static_cast<float>(0.0), static_cast<float>(0.0))
