// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcs-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "fCNDArray.h"
#include "oct-cmplx.h"
#include "fNDArray.h"
SND_BIN_OPS (FloatComplexNDArray, FloatComplex, FloatNDArray)
SND_CMP_OPS (FloatComplex, real, FloatNDArray, )
SND_BOOL_OPS2 (FloatComplex, FloatNDArray, static_cast<float>(0.0), static_cast<float>(0.0))
