// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-i16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int16NDArray, FloatNDArray, int16NDArray)
NDND_CMP_OPS (FloatNDArray, , int16NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, int16NDArray, static_cast<float>(0.0), octave_int16::zero)
