// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fm-fcm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "fCMatrix.h"
#include "fMatrix.h"
MM_BIN_OPS (FloatComplexMatrix, FloatMatrix, FloatComplexMatrix)
MM_CMP_OPS (FloatMatrix, , FloatComplexMatrix, real)
MM_BOOL_OPS2 (FloatMatrix, FloatComplexMatrix, static_cast<float>(0.0), static_cast<float>(0.0))
