// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcm-fm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "fCMatrix.h"
#include "fMatrix.h"
MM_BIN_OPS (FloatComplexMatrix, FloatComplexMatrix, FloatMatrix)
MM_CMP_OPS (FloatComplexMatrix, real, FloatMatrix, )
MM_BOOL_OPS2 (FloatComplexMatrix, FloatMatrix, static_cast<float>(0.0), static_cast<float>(0.0))
