// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-ui32.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "fNDArray.h"
#include "oct-inttypes.h"
NDS_BIN_OPS (uint32NDArray, FloatNDArray, octave_uint32)
NDS_CMP_OPS1 (FloatNDArray, , octave_uint32, , uint32_t)
NDS_BOOL_OPS2 (FloatNDArray, octave_uint32, static_cast<float>(0.0), octave_uint32::zero)
