// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-i32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int32NDArray, FloatNDArray, int32NDArray)
NDND_CMP_OPS (FloatNDArray, , int32NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, int32NDArray, static_cast<float>(0.0), octave_int32::zero)
