// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-i64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
SND_BIN_OPS (int64NDArray, float, int64NDArray)
SND_CMP_OPS1 (float, , int64NDArray, , int64_t)
SND_BOOL_OPS2 (float, int64NDArray, static_cast<float>(0.0), octave_int64::zero)
