// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint8NDArray, FloatNDArray, uint8NDArray)
NDND_CMP_OPS (FloatNDArray, , uint8NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, uint8NDArray, static_cast<float>(0.0), octave_uint8::zero)
