// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fm-fcdm.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "fMatrix.h"
#include "fCDiagMatrix.h"
MDM_BIN_OPS (FloatComplexMatrix, FloatMatrix, FloatComplexDiagMatrix, static_cast<float>(0.0))
