// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-fdm.h"
#include "mx-op-defs.h"
#include "fMatrix.h"
#include "fDiagMatrix.h"
SDM_BIN_OPS (FloatMatrix, float, FloatDiagMatrix)
