// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
SND_BIN_OPS (uint8NDArray, float, uint8NDArray)
SND_CMP_OPS1 (float, , uint8NDArray, , uint8_t)
SND_BOOL_OPS2 (float, uint8NDArray, static_cast<float>(0.0), octave_uint8::zero)
