// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-ui32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint32NDArray, FloatNDArray, uint32NDArray)
NDND_CMP_OPS (FloatNDArray, , uint32NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, uint32NDArray, static_cast<float>(0.0), octave_uint32::zero)
