// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-fcm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "fCMatrix.h"
SM_BIN_OPS (FloatComplexMatrix, float, FloatComplexMatrix)
SM_CMP_OPS (float, , FloatComplexMatrix, real)
SM_BOOL_OPS2 (float, FloatComplexMatrix, static_cast<float>(0.0), static_cast<float>(0.0))
