// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint64NDArray, FloatNDArray, uint64NDArray)
NDND_CMP_OPS (FloatNDArray, , uint64NDArray, )
NDND_BOOL_OPS2 (FloatNDArray, uint64NDArray, static_cast<float>(0.0), octave_uint64::zero)
