// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fnda-fcs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "fCNDArray.h"
#include "fNDArray.h"
#include "oct-cmplx.h"
NDS_BIN_OPS (FloatComplexNDArray, FloatNDArray, FloatComplex)
NDS_CMP_OPS (FloatNDArray, , FloatComplex, real)
NDS_BOOL_OPS2 (FloatNDArray, FloatComplex, static_cast<float>(0.0), static_cast<float>(0.0))
