// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-fcnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "fCNDArray.h"
SND_BIN_OPS (FloatComplexNDArray, float, FloatComplexNDArray)
SND_CMP_OPS (float, , FloatComplexNDArray, real)
SND_BOOL_OPS2 (float, FloatComplexNDArray, static_cast<float>(0.0), static_cast<float>(0.0))
