// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcnda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "fCNDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (FloatComplexNDArray, FloatComplexNDArray, FloatNDArray)
NDND_CMP_OPS (FloatComplexNDArray, real, FloatNDArray, )
NDND_BOOL_OPS2 (FloatComplexNDArray, FloatNDArray, static_cast<float>(0.0), static_cast<float>(0.0))
