// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fm-fdm.h"
#include "mx-op-defs.h"
#include "fMatrix.h"
#include "fDiagMatrix.h"
MDM_BIN_OPS (FloatMatrix, FloatMatrix, FloatDiagMatrix, static_cast<float>(0.0))
