// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcm-fdm.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "fDiagMatrix.h"
MDM_BIN_OPS (FloatComplexMatrix, FloatComplexMatrix, FloatDiagMatrix, static_cast<float>(0.0))
