// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcdm-fcs.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
#include "oct-cmplx.h"
DMS_BIN_OPS (FloatComplexMatrix, FloatComplexDiagMatrix, FloatComplex)
