// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcs-fcdm.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fCDiagMatrix.h"
SDM_BIN_OPS (FloatComplexMatrix, FloatComplex, FloatComplexDiagMatrix)
