// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-ui32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
SND_BIN_OPS (uint32NDArray, float, uint32NDArray)
SND_CMP_OPS1 (float, , uint32NDArray, , uint32_t)
SND_BOOL_OPS2 (float, uint32NDArray, static_cast<float>(0.0), octave_uint32::zero)
