// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-i8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
SND_BIN_OPS (int8NDArray, float, int8NDArray)
SND_CMP_OPS1 (float, , int8NDArray, , int8_t)
SND_BOOL_OPS2 (float, int8NDArray, static_cast<float>(0.0), octave_int8::zero)
