// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcm-pm.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "PermMatrix.h"
MPM_BIN_OPS (FloatComplexMatrix, FloatComplexMatrix, PermMatrix)
