// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcdm-fdm.h"
#include "mx-op-defs.h"
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
DMDM_BIN_OPS (FloatComplexDiagMatrix, FloatComplexDiagMatrix, FloatDiagMatrix)
