// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fcs-fm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fMatrix.h"
SM_BIN_OPS (FloatComplexMatrix, FloatComplex, FloatMatrix)
SM_CMP_OPS (FloatComplex, real, FloatMatrix, )
SM_BOOL_OPS2 (FloatComplex, FloatMatrix, static_cast<float>(0.0), static_cast<float>(0.0))
