// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fs-i16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
SND_BIN_OPS (int16NDArray, float, int16NDArray)
SND_CMP_OPS1 (float, , int16NDArray, , int16_t)
SND_BOOL_OPS2 (float, int16NDArray, static_cast<float>(0.0), octave_int16::zero)
