// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fdm-fcm.h"
#include "mx-op-defs.h"
#include "fCMatrix.h"
#include "fDiagMatrix.h"
DMM_BIN_OPS (FloatComplexMatrix, FloatDiagMatrix, FloatComplexMatrix, static_cast<float>(0.0))
