// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-fdm-fs.h"
#include "mx-op-defs.h"
#include "fMatrix.h"
#include "fDiagMatrix.h"
DMS_BIN_OPS (FloatMatrix, FloatDiagMatrix, float)
