// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-s.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
NDS_BIN_OPS (int16NDArray, int16NDArray, double)
NDS_CMP_OPS1 (int16NDArray, , double, , int16_t)
NDS_BOOL_OPS2 (int16NDArray, double, octave_int16::zero, 0.0)
