// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-s.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
NDS_BIN_OPS (int32NDArray, int32NDArray, double)
NDS_CMP_OPS1 (int32NDArray, , double, , int32_t)
NDS_BOOL_OPS2 (int32NDArray, double, octave_int32::zero, 0.0)
