// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16-i32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int32NDArray.h"
SND_CMP_OPS2 (octave_int16, , int32NDArray, , int16_t, int32_t)
SND_BOOL_OPS2 (octave_int16, int32NDArray, octave_int16::zero, octave_int32::zero)
