// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
SND_BIN_OPS (int8NDArray, octave_int8, FloatNDArray)
SND_CMP_OPS1 (octave_int8, , FloatNDArray, , int8_t)
SND_BOOL_OPS2 (octave_int8, FloatNDArray, octave_int8::zero, static_cast<float>(0.0))
