// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
NDS_BIN_OPS (int64NDArray, int64NDArray, float)
NDS_CMP_OPS1 (int64NDArray, , float, , int64_t)
NDS_BOOL_OPS2 (int64NDArray, float, octave_int64::zero, static_cast<float>(0.0))
