// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int16NDArray, int16NDArray, FloatNDArray)
NDND_CMP_OPS (int16NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (int16NDArray, FloatNDArray, octave_int16::zero, static_cast<float>(0.0))
