// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int64NDArray, int64NDArray, NDArray)
NDND_CMP_OPS (int64NDArray, , NDArray, )
NDND_BOOL_OPS2 (int64NDArray, NDArray, octave_int64::zero, 0.0)
