// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8nda-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "uint16NDArray.h"
NDND_CMP_OPS (int8NDArray, , uint16NDArray, )
NDND_BOOL_OPS2 (int8NDArray, uint16NDArray, octave_int8::zero, octave_uint16::zero)
