// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-ui16.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (int16NDArray, , octave_uint16, , int16_t, uint16_t)
NDS_BOOL_OPS2 (int16NDArray, octave_uint16, octave_int16::zero, octave_uint16::zero)
