// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8nda-ui8.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (int8NDArray, , octave_uint8, , int8_t, uint8_t)
NDS_BOOL_OPS2 (int8NDArray, octave_uint8, octave_int8::zero, octave_uint8::zero)
