// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int8NDArray, int8NDArray, NDArray)
NDND_CMP_OPS (int8NDArray, , NDArray, )
NDND_BOOL_OPS2 (int8NDArray, NDArray, octave_int8::zero, 0.0)
