// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "uint8NDArray.h"
NDND_CMP_OPS (int16NDArray, , uint8NDArray, )
NDND_BOOL_OPS2 (int16NDArray, uint8NDArray, octave_int16::zero, octave_uint8::zero)
