// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16-i64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int64NDArray.h"
SND_CMP_OPS2 (octave_int16, , int64NDArray, , int16_t, int64_t)
SND_BOOL_OPS2 (octave_int16, int64NDArray, octave_int16::zero, octave_int64::zero)
