// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-i32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "int32NDArray.h"
NDND_CMP_OPS (int64NDArray, , int32NDArray, )
NDND_BOOL_OPS2 (int64NDArray, int32NDArray, octave_int64::zero, octave_int32::zero)
