// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int32NDArray, int32NDArray, FloatNDArray)
NDND_CMP_OPS (int32NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (int32NDArray, FloatNDArray, octave_int32::zero, static_cast<float>(0.0))
