// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "uint16NDArray.h"
SND_CMP_OPS2 (octave_int16, , uint16NDArray, , int16_t, uint16_t)
SND_BOOL_OPS2 (octave_int16, uint16NDArray, octave_int16::zero, octave_uint16::zero)
