// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64-i16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int16NDArray.h"
SND_CMP_OPS2 (octave_int64, , int16NDArray, , int64_t, int16_t)
SND_BOOL_OPS2 (octave_int64, int16NDArray, octave_int64::zero, octave_int16::zero)
