// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8nda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
NDS_BIN_OPS (int8NDArray, int8NDArray, float)
NDS_CMP_OPS1 (int8NDArray, , float, , int8_t)
NDS_BOOL_OPS2 (int8NDArray, float, octave_int8::zero, static_cast<float>(0.0))
