// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
SND_BIN_OPS (int64NDArray, octave_int64, FloatNDArray)
SND_CMP_OPS1 (octave_int64, , FloatNDArray, , int64_t)
SND_BOOL_OPS2 (octave_int64, FloatNDArray, octave_int64::zero, static_cast<float>(0.0))
