// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-i16.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (int64NDArray, , octave_int16, , int64_t, int16_t)
NDS_BOOL_OPS2 (int64NDArray, octave_int16, octave_int64::zero, octave_int16::zero)
