// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16-ui32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "uint32NDArray.h"
SND_CMP_OPS2 (octave_int16, , uint32NDArray, , int16_t, uint32_t)
SND_BOOL_OPS2 (octave_int16, uint32NDArray, octave_int16::zero, octave_uint32::zero)
