// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "uint8NDArray.h"
SND_CMP_OPS2 (octave_int32, , uint8NDArray, , int32_t, uint8_t)
SND_BOOL_OPS2 (octave_int32, uint8NDArray, octave_int32::zero, octave_uint8::zero)
