// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i8nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int8NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (int8NDArray, int8NDArray, FloatNDArray)
NDND_CMP_OPS (int8NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (int8NDArray, FloatNDArray, octave_int8::zero, static_cast<float>(0.0))
