// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-ui64.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (int64NDArray, , octave_uint64, , int64_t, uint64_t)
NDS_BOOL_OPS2 (int64NDArray, octave_uint64, octave_int64::zero, octave_uint64::zero)
