// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-i8.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (int16NDArray, , octave_int8, , int16_t, int8_t)
NDS_BOOL_OPS2 (int16NDArray, octave_int8, octave_int16::zero, octave_int8::zero)
