// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "uint16NDArray.h"
NDND_CMP_OPS (int32NDArray, , uint16NDArray, )
NDND_BOOL_OPS2 (int32NDArray, uint16NDArray, octave_int32::zero, octave_uint16::zero)
