// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "uint64NDArray.h"
NDND_CMP_OPS (int32NDArray, , uint64NDArray, )
NDND_BOOL_OPS2 (int32NDArray, uint64NDArray, octave_int32::zero, octave_uint64::zero)
