// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
SND_BIN_OPS (int16NDArray, octave_int16, NDArray)
SND_CMP_OPS1 (octave_int16, , NDArray, , int16_t)
SND_BOOL_OPS2 (octave_int16, NDArray, octave_int16::zero, 0.0)
