// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int16NDArray, int16NDArray, NDArray)
NDND_CMP_OPS (int16NDArray, , NDArray, )
NDND_BOOL_OPS2 (int16NDArray, NDArray, octave_int16::zero, 0.0)
