// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i64nda-s.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
NDS_BIN_OPS (int64NDArray, int64NDArray, double)
NDS_CMP_OPS1 (int64NDArray, , double, , int64_t)
NDS_BOOL_OPS2 (int64NDArray, double, octave_int64::zero, 0.0)
