// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
NDS_BIN_OPS (int32NDArray, int32NDArray, float)
NDS_CMP_OPS1 (int32NDArray, , float, , int32_t)
NDS_BOOL_OPS2 (int32NDArray, float, octave_int32::zero, static_cast<float>(0.0))
