// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i16nda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
NDS_BIN_OPS (int16NDArray, int16NDArray, float)
NDS_CMP_OPS1 (int16NDArray, , float, , int16_t)
NDS_BOOL_OPS2 (int16NDArray, float, octave_int16::zero, static_cast<float>(0.0))
