// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-i32nda-i16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "int16NDArray.h"
NDND_CMP_OPS (int32NDArray, , int16NDArray, )
NDND_BOOL_OPS2 (int32NDArray, int16NDArray, octave_int32::zero, octave_int16::zero)
