// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-m-cdm.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "dMatrix.h"
#include "CDiagMatrix.h"
MDM_BIN_OPS (ComplexMatrix, Matrix, ComplexDiagMatrix, 0.0)
