// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-m-dm.h"
#include "mx-op-defs.h"
#include "dMatrix.h"
#include "dDiagMatrix.h"
MDM_BIN_OPS (Matrix, Matrix, DiagMatrix, 0.0)
