// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-m-cm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "CMatrix.h"
#include "dMatrix.h"
MM_BIN_OPS (ComplexMatrix, Matrix, ComplexMatrix)
MM_CMP_OPS (Matrix, , ComplexMatrix, real)
MM_BOOL_OPS2 (Matrix, ComplexMatrix, 0.0, 0.0)
