// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-ui32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint32NDArray, NDArray, uint32NDArray)
NDND_CMP_OPS (NDArray, , uint32NDArray, )
NDND_BOOL_OPS2 (NDArray, uint32NDArray, 0.0, octave_uint32::zero)
