// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int16NDArray, NDArray, int16NDArray)
NDND_CMP_OPS (NDArray, , int16NDArray, )
NDND_BOOL_OPS2 (NDArray, int16NDArray, 0.0, octave_int16::zero)
