// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint8NDArray, NDArray, uint8NDArray)
NDND_CMP_OPS (NDArray, , uint8NDArray, )
NDND_BOOL_OPS2 (NDArray, uint8NDArray, 0.0, octave_uint8::zero)
