// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int64NDArray, NDArray, int64NDArray)
NDND_CMP_OPS (NDArray, , int64NDArray, )
NDND_BOOL_OPS2 (NDArray, int64NDArray, 0.0, octave_int64::zero)
