// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint64NDArray, NDArray, uint64NDArray)
NDND_CMP_OPS (NDArray, , uint64NDArray, )
NDND_BOOL_OPS2 (NDArray, uint64NDArray, 0.0, octave_uint64::zero)
