// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint16NDArray, NDArray, uint16NDArray)
NDND_CMP_OPS (NDArray, , uint16NDArray, )
NDND_BOOL_OPS2 (NDArray, uint16NDArray, 0.0, octave_uint16::zero)
