// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i32.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
NDS_BIN_OPS (int32NDArray, NDArray, octave_int32)
NDS_CMP_OPS1 (NDArray, , octave_int32, , int32_t)
NDS_BOOL_OPS2 (NDArray, octave_int32, 0.0, octave_int32::zero)
