// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i16.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int16NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
NDS_BIN_OPS (int16NDArray, NDArray, octave_int16)
NDS_CMP_OPS1 (NDArray, , octave_int16, , int16_t)
NDS_BOOL_OPS2 (NDArray, octave_int16, 0.0, octave_int16::zero)
