// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i32nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int32NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (int32NDArray, NDArray, int32NDArray)
NDND_CMP_OPS (NDArray, , int32NDArray, )
NDND_BOOL_OPS2 (NDArray, int32NDArray, 0.0, octave_int32::zero)
