// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-nda-i64.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "int64NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
NDS_BIN_OPS (int64NDArray, NDArray, octave_int64)
NDS_CMP_OPS1 (NDArray, , octave_int64, , int64_t)
NDS_BOOL_OPS2 (NDArray, octave_int64, 0.0, octave_int64::zero)
