// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-pm-cm.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "PermMatrix.h"
PMM_BIN_OPS (ComplexMatrix, PermMatrix, ComplexMatrix)
