// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-s-cdm.h"
#include "mx-op-defs.h"
#include "CMatrix.h"
#include "CDiagMatrix.h"
SDM_BIN_OPS (ComplexMatrix, double, ComplexDiagMatrix)
