// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-s-cnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "CNDArray.h"
SND_BIN_OPS (ComplexNDArray, double, ComplexNDArray)
SND_CMP_OPS (double, , ComplexNDArray, real)
SND_BOOL_OPS2 (double, ComplexNDArray, 0.0, 0.0)
