// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-s-dm.h"
#include "mx-op-defs.h"
#include "dMatrix.h"
#include "dDiagMatrix.h"
SDM_BIN_OPS (Matrix, double, DiagMatrix)
