// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-s-ui8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
SND_BIN_OPS (uint8NDArray, double, uint8NDArray)
SND_CMP_OPS1 (double, , uint8NDArray, , uint8_t)
SND_BOOL_OPS2 (double, uint8NDArray, 0.0, octave_uint8::zero)
