// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-s-cm.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "CMatrix.h"
SM_BIN_OPS (ComplexMatrix, double, ComplexMatrix)
SM_CMP_OPS (double, , ComplexMatrix, real)
SM_BOOL_OPS2 (double, ComplexMatrix, 0.0, 0.0)
