// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui32nda-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "uint64NDArray.h"
NDND_CMP_OPS (uint32NDArray, , uint64NDArray, )
NDND_BOOL_OPS2 (uint32NDArray, uint64NDArray, octave_uint32::zero, octave_uint64::zero)
