// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16-i8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int8NDArray.h"
SND_CMP_OPS2 (octave_uint16, , int8NDArray, , uint16_t, int8_t)
SND_BOOL_OPS2 (octave_uint16, int8NDArray, octave_uint16::zero, octave_int8::zero)
