// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8nda-i64.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (uint8NDArray, , octave_int64, , uint8_t, int64_t)
NDS_BOOL_OPS2 (uint8NDArray, octave_int64, octave_uint8::zero, octave_int64::zero)
