// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
SND_BIN_OPS (uint64NDArray, octave_uint64, NDArray)
SND_CMP_OPS1 (octave_uint64, , NDArray, , uint64_t)
SND_BOOL_OPS2 (octave_uint64, NDArray, octave_uint64::zero, 0.0)
