// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "uint16NDArray.h"
SND_CMP_OPS2 (octave_uint64, , uint16NDArray, , uint64_t, uint16_t)
SND_BOOL_OPS2 (octave_uint64, uint16NDArray, octave_uint64::zero, octave_uint16::zero)
