// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
SND_BIN_OPS (uint16NDArray, octave_uint16, NDArray)
SND_CMP_OPS1 (octave_uint16, , NDArray, , uint16_t)
SND_BOOL_OPS2 (octave_uint16, NDArray, octave_uint16::zero, 0.0)
