// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint64NDArray, uint64NDArray, NDArray)
NDND_CMP_OPS (uint64NDArray, , NDArray, )
NDND_BOOL_OPS2 (uint64NDArray, NDArray, octave_uint64::zero, 0.0)
