// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16nda-s.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
NDS_BIN_OPS (uint16NDArray, uint16NDArray, double)
NDS_CMP_OPS1 (uint16NDArray, , double, , uint16_t)
NDS_BOOL_OPS2 (uint16NDArray, double, octave_uint16::zero, 0.0)
