// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint64NDArray, uint64NDArray, FloatNDArray)
NDND_CMP_OPS (uint64NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (uint64NDArray, FloatNDArray, octave_uint64::zero, static_cast<float>(0.0))
