// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
SND_BIN_OPS (uint8NDArray, octave_uint8, NDArray)
SND_CMP_OPS1 (octave_uint8, , NDArray, , uint8_t)
SND_BOOL_OPS2 (octave_uint8, NDArray, octave_uint8::zero, 0.0)
