// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16-i64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int64NDArray.h"
SND_CMP_OPS2 (octave_uint16, , int64NDArray, , uint16_t, int64_t)
SND_BOOL_OPS2 (octave_uint16, int64NDArray, octave_uint16::zero, octave_int64::zero)
