// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64-i64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "int64NDArray.h"
SND_CMP_OPS2 (octave_uint64, , int64NDArray, , uint64_t, int64_t)
SND_BOOL_OPS2 (octave_uint64, int64NDArray, octave_uint64::zero, octave_int64::zero)
