// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16nda-ui64.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (uint16NDArray, , octave_uint64, , uint16_t, uint64_t)
NDS_BOOL_OPS2 (uint16NDArray, octave_uint64, octave_uint16::zero, octave_uint64::zero)
