// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui32-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
SND_BIN_OPS (uint32NDArray, octave_uint32, NDArray)
SND_CMP_OPS1 (octave_uint32, , NDArray, , uint32_t)
SND_BOOL_OPS2 (octave_uint32, NDArray, octave_uint32::zero, 0.0)
