// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui32nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint32NDArray, uint32NDArray, FloatNDArray)
NDND_CMP_OPS (uint32NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (uint32NDArray, FloatNDArray, octave_uint32::zero, static_cast<float>(0.0))
