// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16nda-fs.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
NDS_BIN_OPS (uint16NDArray, uint16NDArray, float)
NDS_CMP_OPS1 (uint16NDArray, , float, , uint16_t)
NDS_BOOL_OPS2 (uint16NDArray, float, octave_uint16::zero, static_cast<float>(0.0))
