// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
SND_BIN_OPS (uint8NDArray, octave_uint8, FloatNDArray)
SND_CMP_OPS1 (octave_uint8, , FloatNDArray, , uint8_t)
SND_BOOL_OPS2 (octave_uint8, FloatNDArray, octave_uint8::zero, static_cast<float>(0.0))
