// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64nda-ui32.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (uint64NDArray, , octave_uint32, , uint64_t, uint32_t)
NDS_BOOL_OPS2 (uint64NDArray, octave_uint32, octave_uint64::zero, octave_uint32::zero)
