// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "oct-inttypes.h"
#include "uint64NDArray.h"
SND_CMP_OPS2 (octave_uint8, , uint64NDArray, , uint8_t, uint64_t)
SND_BOOL_OPS2 (octave_uint8, uint64NDArray, octave_uint8::zero, octave_uint64::zero)
