// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint8NDArray, uint8NDArray, NDArray)
NDND_CMP_OPS (uint8NDArray, , NDArray, )
NDND_BOOL_OPS2 (uint8NDArray, NDArray, octave_uint8::zero, 0.0)
