// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui32nda-ui16.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint32NDArray.h"
#include "oct-inttypes.h"
NDS_CMP_OPS2 (uint32NDArray, , octave_uint16, , uint32_t, uint16_t)
NDS_BOOL_OPS2 (uint32NDArray, octave_uint16, octave_uint32::zero, octave_uint16::zero)
