// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8nda-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "fNDArray.h"
NDND_BIN_OPS (uint8NDArray, uint8NDArray, FloatNDArray)
NDND_CMP_OPS (uint8NDArray, , FloatNDArray, )
NDND_BOOL_OPS2 (uint8NDArray, FloatNDArray, octave_uint8::zero, static_cast<float>(0.0))
