// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64-fnda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
SND_BIN_OPS (uint64NDArray, octave_uint64, FloatNDArray)
SND_CMP_OPS1 (octave_uint64, , FloatNDArray, , uint64_t)
SND_BOOL_OPS2 (octave_uint64, FloatNDArray, octave_uint64::zero, static_cast<float>(0.0))
