// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui16nda-nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint16NDArray.h"
#include "dNDArray.h"
NDND_BIN_OPS (uint16NDArray, uint16NDArray, NDArray)
NDND_CMP_OPS (uint16NDArray, , NDArray, )
NDND_BOOL_OPS2 (uint16NDArray, NDArray, octave_uint16::zero, 0.0)
