// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64nda-ui16nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "uint16NDArray.h"
NDND_CMP_OPS (uint64NDArray, , uint16NDArray, )
NDND_BOOL_OPS2 (uint64NDArray, uint16NDArray, octave_uint64::zero, octave_uint16::zero)
