// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui8nda-ui64nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint8NDArray.h"
#include "uint64NDArray.h"
NDND_CMP_OPS (uint8NDArray, , uint64NDArray, )
NDND_BOOL_OPS2 (uint8NDArray, uint64NDArray, octave_uint8::zero, octave_uint64::zero)
