// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-ui64nda-i8nda.h"
#include "mx-op-defs.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "uint64NDArray.h"
#include "int8NDArray.h"
NDND_CMP_OPS (uint64NDArray, , int8NDArray, )
NDND_BOOL_OPS2 (uint64NDArray, int8NDArray, octave_uint64::zero, octave_int8::zero)
