// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-cm-sm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
SPARSE_MSM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, ComplexMatrix, SparseMatrix)
SPARSE_MSM_CMP_OPS (ComplexMatrix, 0.0, real, SparseMatrix, 0.0, )
SPARSE_MSM_BOOL_OPS2 (ComplexMatrix, SparseMatrix, 0.0, 0.0)
