// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-sbm-bm.h"
#include "boolMatrix.h"
#include "boolSparse.h"
SPARSE_SMM_EQNE_OPS (SparseBoolMatrix, false, , boolMatrix, false, )
SPARSE_SMM_BOOL_OPS2 (SparseBoolMatrix, boolMatrix, false, false)
