// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-s-scm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "CSparse.h"
SPARSE_SSM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, double, SparseComplexMatrix)
SPARSE_SSM_CMP_OPS (double, 0.0, , SparseComplexMatrix, 0.0, real)
SPARSE_SSM_BOOL_OPS2 (double, SparseComplexMatrix, 0.0, 0.0)
