// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-sm-scm.h"
#include "boolSparse.h"
#include "CSparse.h"
#include "dSparse.h"
SPARSE_SMSM_BIN_OPS (SparseComplexMatrix, SparseComplexMatrix, SparseMatrix, SparseComplexMatrix)
SPARSE_SMSM_CMP_OPS (SparseMatrix, 0.0, , SparseComplexMatrix, 0.0, real)
SPARSE_SMSM_BOOL_OPS2 (SparseMatrix, SparseComplexMatrix, 0.0, 0.0)
