// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-scm-cm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
SPARSE_SMM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, ComplexMatrix)
SPARSE_SMM_CMP_OPS (SparseComplexMatrix, 0.0, real, ComplexMatrix, 0.0, real)
SPARSE_SMM_BOOL_OPS2 (SparseComplexMatrix, ComplexMatrix, 0.0, 0.0)
