// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-scm-sm.h"
#include "boolSparse.h"
#include "CSparse.h"
#include "dSparse.h"
SPARSE_SMSM_BIN_OPS (SparseComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, SparseMatrix)
SPARSE_SMSM_CMP_OPS (SparseComplexMatrix, 0.0, real, SparseMatrix, 0.0, )
SPARSE_SMSM_BOOL_OPS2 (SparseComplexMatrix, SparseMatrix, 0.0, 0.0)
