// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-m-sm.h"
#include "boolSparse.h"
#include "dMatrix.h"
#include "dSparse.h"
#include "dSparse.h"
SPARSE_MSM_BIN_OPS (Matrix, SparseMatrix, Matrix, SparseMatrix)
SPARSE_MSM_CMP_OPS (Matrix, 0.0, , SparseMatrix, 0.0, )
SPARSE_MSM_BOOL_OPS2 (Matrix, SparseMatrix, 0.0, 0.0)
