// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-cs-sm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "oct-cmplx.h"
#include "dSparse.h"
SPARSE_SSM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, Complex, SparseMatrix)
SPARSE_SSM_CMP_OPS (Complex, 0.0, real, SparseMatrix, 0.0, )
SPARSE_SSM_BOOL_OPS2 (Complex, SparseMatrix, 0.0, 0.0)
