// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-sm-m.h"
#include "boolSparse.h"
#include "dMatrix.h"
#include "dSparse.h"
SPARSE_SMM_BIN_OPS (Matrix, SparseMatrix, SparseMatrix, Matrix)
SPARSE_SMM_CMP_OPS (SparseMatrix, 0.0, , Matrix, 0.0, )
SPARSE_SMM_BOOL_OPS2 (SparseMatrix, Matrix, 0.0, 0.0)
