// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-m-scm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dMatrix.h"
#include "CSparse.h"
SPARSE_MSM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, Matrix, SparseComplexMatrix)
SPARSE_MSM_CMP_OPS (Matrix, 0.0, , SparseComplexMatrix, 0.0, real)
SPARSE_MSM_BOOL_OPS2 (Matrix, SparseComplexMatrix, 0.0, 0.0)
