// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-bm-sbm.h"
#include "boolMatrix.h"
#include "boolSparse.h"
#include "boolSparse.h"
SPARSE_MSM_EQNE_OPS (boolMatrix, false, , SparseBoolMatrix, false, )
SPARSE_MSM_BOOL_OPS2 (boolMatrix, SparseBoolMatrix, false, false)
