// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-scm-m.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dMatrix.h"
SPARSE_SMM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, Matrix)
SPARSE_SMM_CMP_OPS (SparseComplexMatrix, 0.0, real, Matrix, 0.0, )
SPARSE_SMM_BOOL_OPS2 (SparseComplexMatrix, Matrix, 0.0, 0.0)
