// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-sm-cs.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
#include "oct-cmplx.h"
SPARSE_SMS_BIN_OPS (ComplexMatrix, SparseComplexMatrix, SparseMatrix, Complex)
SPARSE_SMS_CMP_OPS (SparseMatrix, 0.0, , Complex, 0.0, real)
SPARSE_SMS_BOOL_OPS2 (SparseMatrix, Complex, 0.0, 0.0)
