// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-sm-cm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
SPARSE_SMM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, SparseMatrix, ComplexMatrix)
SPARSE_SMM_CMP_OPS (SparseMatrix, 0.0, , ComplexMatrix, 0.0, real)
SPARSE_SMM_BOOL_OPS2 (SparseMatrix, ComplexMatrix, 0.0, 0.0)
