// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-scm-s.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
SPARSE_SMS_BIN_OPS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, double)
SPARSE_SMS_CMP_OPS (SparseComplexMatrix, 0.0, real, double, 0.0, )
SPARSE_SMS_BOOL_OPS2 (SparseComplexMatrix, double, 0.0, 0.0)
