// DO NOT EDIT -- generated by sparse-mk-ops
#include <config.h>
#include "Array-util.h"
#include "quit.h"
#include "smx-cm-scm.h"
#include "boolSparse.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "CSparse.h"
SPARSE_MSM_BIN_OPS (ComplexMatrix, SparseComplexMatrix, ComplexMatrix, SparseComplexMatrix)
SPARSE_MSM_CMP_OPS (ComplexMatrix, 0.0, real, SparseComplexMatrix, 0.0, real)
SPARSE_MSM_BOOL_OPS2 (ComplexMatrix, SparseComplexMatrix, 0.0, 0.0)
