// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-cs-cv.h"
#include "mx-op-defs.h"
#include "CColVector.h"
#include "oct-cmplx.h"
#include "dColVector.h"
SV_BIN_OPS (ComplexColumnVector, Complex, ColumnVector)
