// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-cv-ccv.h"
#include "mx-op-defs.h"
#include "CColVector.h"
#include "dColVector.h"
VV_BIN_OPS (ComplexColumnVector, ColumnVector, ComplexColumnVector)
