// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-cv-cs.h"
#include "mx-op-defs.h"
#include "CColVector.h"
#include "dColVector.h"
#include "oct-cmplx.h"
VS_BIN_OPS (ComplexColumnVector, ColumnVector, Complex)
