// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-crv-s.h"
#include "mx-op-defs.h"
#include "CRowVector.h"
VS_BIN_OPS (ComplexRowVector, ComplexRowVector, double)
