// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fccv-fs.h"
#include "mx-op-defs.h"
#include "fCColVector.h"
VS_BIN_OPS (FloatComplexColumnVector, FloatComplexColumnVector, float)
