// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fcs-fcv.h"
#include "mx-op-defs.h"
#include "fCColVector.h"
#include "oct-cmplx.h"
#include "fColVector.h"
SV_BIN_OPS (FloatComplexColumnVector, FloatComplex, FloatColumnVector)
