// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fccv-fcv.h"
#include "mx-op-defs.h"
#include "fCColVector.h"
#include "fColVector.h"
VV_BIN_OPS (FloatComplexColumnVector, FloatComplexColumnVector, FloatColumnVector)
