// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fcv-fcs.h"
#include "mx-op-defs.h"
#include "fCColVector.h"
#include "fColVector.h"
#include "oct-cmplx.h"
VS_BIN_OPS (FloatComplexColumnVector, FloatColumnVector, FloatComplex)
