// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fcs-frv.h"
#include "mx-op-defs.h"
#include "fCRowVector.h"
#include "oct-cmplx.h"
#include "fRowVector.h"
SV_BIN_OPS (FloatComplexRowVector, FloatComplex, FloatRowVector)
