// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fs-fccv.h"
#include "mx-op-defs.h"
#include "fCColVector.h"
SV_BIN_OPS (FloatComplexColumnVector, float, FloatComplexColumnVector)
