// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fcrv-fs.h"
#include "mx-op-defs.h"
#include "fCRowVector.h"
VS_BIN_OPS (FloatComplexRowVector, FloatComplexRowVector, float)
