// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-fs-fcrv.h"
#include "mx-op-defs.h"
#include "fCRowVector.h"
SV_BIN_OPS (FloatComplexRowVector, float, FloatComplexRowVector)
