// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-rv-cs.h"
#include "mx-op-defs.h"
#include "CRowVector.h"
#include "dRowVector.h"
#include "oct-cmplx.h"
VS_BIN_OPS (ComplexRowVector, RowVector, Complex)
