// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "vx-s-ccv.h"
#include "mx-op-defs.h"
#include "CColVector.h"
SV_BIN_OPS (ComplexColumnVector, double, ComplexColumnVector)
