#!/bin/sh -e
#
# prerm script for the Debian GNU/Linux octave package
#
# Originally written by Dirk Eddelbuettel <edd@debian.org>

#DEBHELPER#

case "$1" in
    remove|upgrade|deconfigure)
	# This is for old installations of the octave package
	if [ -f /usr/share/octave/ls-R ]
	then
	    rm -f /usr/share/octave/ls-R
	fi

	;;
    failed-upgrade)
	;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

