#!/bin/sh
#
# This is the prerm script for the Debian GNU/Linux octave-htmldoc package
#
# Written by Dirk Eddelbuettel <edd@debian.org>   

set -e

#DEBHELPER#

# nothing needed beyond what debhelper already provides
case "$1" in
    upgrade)
	;;
    remove|purge)
	;;
    failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	;;
esac

exit 0
